lib/idea_snippets_web/router.ex
defmodule IdeaSnippetsWeb.Router do
  use IdeaSnippetsWeb, :router

  import IdeaSnippetsWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IdeaSnippetsWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", IdeaSnippetsWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: IdeaSnippetsWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", IdeaSnippetsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", IdeaSnippetsWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    resources "/posts", PostController do
      post "/comment", PostController, :add_comment
    end
  end

  scope "/", IdeaSnippetsWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/idea_snippets/codes/post.ex
defmodule IdeaSnippets.Codes.Post do
  use Ecto.Schema
  import Ecto.Changeset
  alias IdeaSnippets.Comments.Comment

  schema "posts" do
    field :title, :string
    field :description, :string
    field :code, :string
    field :user_id, :integer
    has_many(:comments, Comment)

    field :published, Ecto.Enum, values: [:draft, :public, :limited, :private]


    timestamps()
  end

  @doc false
  def changeset(post, attrs) do
    post
    |> cast(attrs, [:title, :description, :code, :user_id, :published])
    |> validate_required([:title, :description, :code, :user_id, :published])
  end
end

lib/idea_snippets_web/controllers/post_controller.ex
defmodule IdeaSnippetsWeb.PostController do
  use IdeaSnippetsWeb, :controller

  alias IdeaSnippets.Codes
  alias IdeaSnippets.Codes.Post
  alias IdeaSnippets.Repo
  alias IdeaSnippets.Comments.Comment

  def index(conn, _params) do
    posts = Codes.list_posts(conn.assigns.current_user.id)
    render(conn, "index.html", posts: posts)
  end

  def new(conn, _params) do
    changeset = Codes.change_post(%Post{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    case Codes.create_post(post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: Routes.post_path(conn, :show, post))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Codes.get_comments(id)
    changeset = Comment.changeset(%Comment{}, %{})
    render(conn, "show.html", post: post, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    post = Codes.get_post!(id)
    changeset = Codes.change_post(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Codes.get_post!(id)

    case Codes.update_post(post, post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: Routes.post_path(conn, :show, post))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Codes.get_post!(id)
    {:ok, _post} = Codes.delete_post(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: Routes.post_path(conn, :index))
  end

  def add_comment(conn, %{"comment" => comment_params, "post_id" => post_id}) do
    post = Codes.get_post!(post_id)

    case Codes.add_comment(post_id, comment_params) do
      {:ok, _comment} ->
        conn
        |> put_flash(:info, "Comment added !")
        |> redirect(to: Routes.post_path(conn, :show, post))
      {:error, _error} ->
        conn
        |> put_flash(:error, "Comment not added.")
        |> redirect(to: Routes.post_path(conn, :show, post))

    end
  end




end

lib/idea_snippets_web/views/post_view.ex
defmodule IdeaSnippetsWeb.PostView do
  use IdeaSnippetsWeb, :view
  alias IdeaSnippets.Codes

def get_number_of_comments(post_id) do
  post = Codes.get_comments(post_id)
  Enum.count(post.comments)
end


def parse_markdown(markdown) do
  Earmark.as_html!(markdown, %Earmark.Options{code_class_prefix: "lang-", smartypants: false})
end

end

lib/idea_snippets_web/templates/post/comments.html.eex
<h3>Comments:</h3>
<div class="comments">
 <div class="comment header">
 <div>Name</div>
 <div>Content</div>
 </div>
<%= for comment <- @comments do %>
 <div class="comment" >
 <div><%= comment.name %></div>
 <div><%= comment.content %></div>
 </div>
<% end %>
</div>

lib/idea_snippets_web/templates/post/comments_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
 <%= if @changeset.action do %>
 <div class="alert alert-danger">
 <p>Oops, something went wrong! Please check the errors below.</p>
 </div>
 <% end %>
 <%= label f, :name, class: "form-group" %>
 <%= text_input f, :name, class: "form-control" %>
 <%= error_tag f, :name %>
 <%= label f, :content, class: "form-group" %>
 <%= textarea f, :content, class: "form-control" %>
 <%= error_tag f, :content %>
 <div class="form-group">
 <%= submit "Add comment", class: "btn btn-primary" %>
 </div>
<% end %>

lib/idea_snippets_web/templates/post/edit.html.eex
<h1>Edit Post</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.post_path(@conn, :update, @post)) %>

<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>

lib/idea_snippets_web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :description %>
  <%= text_input f, :description %>
  <%= error_tag f, :description %>

  <%= label f, :code %>
  <%= textarea f, :code %>
  <%= error_tag f, :code %>

  <%= label f, :published %>
  <%= select f, :published, [:draft, :public, :limited, :private], value: :draft%>
  <%= error_tag f, :published %>

  <%= if @current_user do %>
  <%= hidden_input f, :user_id, value: @current_user.id %>
  <% end %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/idea_snippets_web/templates/post/index.html.eex
<h1>Listing Posts</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Code</th>
      <th>Comments</th>
      <th>Status</th>
      <th>User_id</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for post <- @posts do %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.description %></td>
      <td><%= parse_markdown(post.code) |> raw %></td>
      <td><%= get_number_of_comments(post.id) %></td>
      <td><%= post.published %></td>
      <td><%= post.user_id %></td>
      <td>
        <span><%= link "Show", to: Routes.post_path(@conn, :show, post) %></span>
        <span><%= link "Edit", to: Routes.post_path(@conn, :edit, post) %></span>
        <span><%= link "Delete", to: Routes.post_path(@conn, :delete, post), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Post", to: Routes.post_path(@conn, :new) %></span>

lib/idea_snippets_web/templates/post/new.html.eex
<h1>New Post</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.post_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>

lib/idea_snippets_web/templates/post/show.html.eex
<h1>Show Post</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @post.description %>
  </li>

  <li>
    <strong>Code:</strong>
    <%= parse_markdown(@post.code) |> raw %>
  </li>

  <li>
    <strong>Show:</strong>
    <%= @post.published %>
  </li>

</ul>

<%= render "comments.html", comments: @post.comments %>
<%= render "comments_form.html", post: @post, changeset: @changeset, action: Routes.post_post_path(@conn, :add_comment, @post) %>

<span><%= link "Edit", to: Routes.post_path(@conn, :edit, @post) %></span>
<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>